name: 'Dockle - Container Image Linter'
description: 'Scans container image configurations'
author: 'Tomoya AMACHI'
inputs:
  image:
    description: 'target container image name'
    required: true
  exit-code:
    description: 'exit code when notifications were found'
    required: false
    default: '1'
  exit-level:
    description: 'exit level when notifications were found'
    required: false
    default: 'warn'
  output:
    description: 'writes results to a file with the specified file name'
    required: false
    default: ''
  format:
    description: 'output format (list, json, sarif)'
    required: false
    default: 'list'
  ignore:
    description: 'comma-separated list of code'
    required: false
    default: ''
  accept-key:
    description: 'Accept suspicious environment variables'
    required: false
    default: ''
  accept-file:
    description: 'Accept suspicious file names'
    required: false
    default: ''
  accept-file-extension:
    description: 'Accept suspicious file extensions'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -t ${{ inputs.image }}
    - -c ${{ inputs.exit-code }}
    - -l ${{ inputs.exit-level }}
    - -f ${{ inputs.format }}
    - -o ${{ inputs.output }}
